### PR TITLE
CORE-2858 fix hardcoded host and port for rabbit mq api

### PR DESCRIPTION
**Pull request by stereomon**
https://spryker.atlassian.net/browse/CORE-2858

Allo configuration of api host and port.

### CODE REVIEW

**Comment by dereuromark** [comment]
Whats the different to the work tamas did yesterday? https://github.com/spryker/rabbit-mq/pull/9/

**Comment by dereuromark** [comment]
If we should release this along with the other PRs now, please resolve the conflicts.

**Comment by ehsanmx** [comment]
@stereomon probably all these fixes are in the other PR  #9

**Comment by stereomon** [comment]
ALready solved in https://github.com/spryker/rabbit-mq/pull/9

**Pull request closed without merging**
