### PR TITLE
TE-28: Fixed return types in Queue

### PR DESCRIPTION
**Pull request by ostrizhny**
- Developer(s): @ostrizhny

- Ticket: https://spryker.atlassian.net/browse/TE-28

- Academy PR: ACADEMY_URL_HERE

- Release Group: https://release.spryker.com/release-groups/view/1107

- Release Overview: https://release.spryker.com/release/pull-request-core/RabbitMq/25

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   RabbitMq                 | minor          |       Queue                |

#### Release Notes

Corrected return types in RabbitMq for `acknowledge()` and `reject()` methods

-----------------------------------------

##### Change log

Improvements

- Fixed return type for `\Spryker\Client\RabbitMq\Model\RabbitMqAdapter::acknowledge()`.
- Fixed return type for `\Spryker\Client\RabbitMq\Model\RabbitMqAdapter::reject()`.

### CODE REVIEW

**Comment by dereuromark** [comment]
isnt there a constraint missing?

**Comment by ostrizhny** [comment]
> isnt there a constraint missing?

Thanks!

**Comment by ostrizhny** [comment]
@dereuromark, build of this PR has failed. Should I correct code style to make it successful in a border of this task?

**Comment by dereuromark** [comment]
You can either make a separate cs fix branch to merge right away into master, or include it here
The separate branch would be cleaner IMO.

**Pull request merged**
